version: '3.7'
services: 
    app: 
        build: 
            args:
                user: llopez
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        container_name: laravel-app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./src:/var/www
        networks:
            - network-app
    db:
        image: mysql:5.7
        container_name: mysql-app
        restart: unless-stopped
        ports: 
            - 33060:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
        - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
        - network-app
    
    nginx:
        image: nginx:alpine
        container_name: nginx-app
        restart: unless-stopped
        ports: 
            - 8000:80
        volumes:
            - ./src:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - network-app
        
networks:
    network-app:
        driver: bridge
